### PR TITLE
Revert "improved Random Error to please pylint"

### PR DESCRIPTION
**Pull request by GastricFluid**
Reverts internisland/InternIsland#9

oops, thought that dev was for developing not the final repo

### CODE REVIEW

**Comment by alicon** [comment]
Don't use the revert feature of git hub. It sucks. 

You can put code into dev that has been unit tested and is not known to have a bugs or be broken (of course in reality it will have bugs, but as far as you know it won't break). 

master should have the latest release of the code and should be extremely stable.

**Comment by alicon** [comment]
Leave it in for now, the revert feature modified the code to make it be like is used to be, so moves the edit time to the future, this messes up future pull requests because it thinks these files are newer than they really are.

**Comment by internisland** [comment]
I accidentally merged the latest pull request which pulled to master instead of dev... Is there a way to 'undo' that without revert?
-Samantha

**Comment by alicon** [comment]
No, nothing easy. 

But it's OK, your project is rather simple. 

Looks like the target of this revert is dev though. Is that intentional?

**Pull request closed without merging**
